defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: Gabriel
  password:
#
# configure :development do
#  db = URI.parse('postgres://postgres:Gabriel@localhost/development')


development:
  <<: *defaults
  database: league
  host: localhost
